2021-05-09 10:32:39,299 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting env: {}
2021-05-09 10:32:39,300 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-09 10:32:39,300 INFO    MainThread:14540 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_103239-2t9lldmm\logs\debug.log
2021-05-09 10:32:39,301 INFO    MainThread:14540 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_103239-2t9lldmm\logs\debug-internal.log
2021-05-09 10:32:39,302 INFO    MainThread:14540 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000027BEB9B1B80>
2021-05-09 10:32:39,302 INFO    MainThread:14540 [wandb_init.py:init():369] calling init triggers
2021-05-09 10:32:39,302 INFO    MainThread:14540 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 600, 'learningRate': 0.0001, 'batchSize': 128, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': True}
2021-05-09 10:32:39,303 INFO    MainThread:14540 [wandb_init.py:init():418] starting backend
2021-05-09 10:32:39,303 INFO    MainThread:14540 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-05-09 10:32:39,307 INFO    MainThread:14540 [backend.py:ensure_launched():123] starting backend process...
2021-05-09 10:32:39,436 INFO    MainThread:14540 [backend.py:ensure_launched():127] started backend process with pid: 15480
2021-05-09 10:32:39,437 INFO    MainThread:14540 [wandb_init.py:init():423] backend started and connected
2021-05-09 10:32:39,455 INFO    MainThread:14540 [wandb_init.py:init():465] updated telemetry
2021-05-09 10:32:39,456 INFO    MainThread:14540 [wandb_init.py:init():484] communicating current version
2021-05-09 10:32:41,295 INFO    MainThread:14540 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-09 10:32:41,296 INFO    MainThread:14540 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-09 10:32:41,789 INFO    MainThread:14540 [wandb_init.py:init():522] starting run threads in backend
2021-05-09 10:32:42,920 INFO    MainThread:14540 [wandb_run.py:_console_start():1554] atexit reg
2021-05-09 10:32:42,921 INFO    MainThread:14540 [wandb_run.py:_redirect():1401] redirect: SettingsConsole.WRAP
2021-05-09 10:32:42,922 INFO    MainThread:14540 [wandb_run.py:_redirect():1444] Wrapping output streams.
2021-05-09 10:32:42,922 INFO    MainThread:14540 [wandb_run.py:_redirect():1468] Redirects installed.
2021-05-09 10:32:42,922 INFO    MainThread:14540 [wandb_init.py:init():546] run started, returning control to user process
2021-05-09 10:32:42,922 INFO    MainThread:14540 [wandb_watch.py:watch():39] Watching
2021-05-09 10:32:42,942 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:42,943 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:32:49,662 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:32:49,671 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:49,672 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:32:49,979 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:32:49,985 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:49,985 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:32:52,599 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:32:52,615 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:52,615 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:32:54,029 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:32:54,033 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:54,034 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:32:54,650 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:32:54,671 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:54,671 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:32:55,979 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:32:55,985 INFO    MainThread:14540 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-09 10:32:55,985 INFO    MainThread:14540 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-09 10:33:04,610 INFO    MainThread:14540 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-09 10:33:05,278 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting env: {}
2021-05-09 10:33:05,278 INFO    MainThread:14540 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-09 10:33:05,278 INFO    MainThread:14540 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_103305-3bh2jmhm\logs\debug.log
2021-05-09 10:33:05,279 INFO    MainThread:14540 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\Steven\Documents\Github\ML\Proyectos\Proyecto II\wandb\run-20210509_103305-3bh2jmhm\logs\debug-internal.log
2021-05-09 10:33:05,279 INFO    MainThread:14540 [wandb_init.py:init():369] calling init triggers
2021-05-09 10:33:05,280 INFO    MainThread:14540 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'epochs': 600, 'learningRate': 0.0001, 'batchSize': 128, 'inputSize': 256, 'fc_size_1': 256, 'fc_size_2': 128, 'fc_size_3': 64, 'fc_size_4': 32, 'fc_size_5': 16, 'fc_size_6': 8, 'outputSize': 4, 'classes': ['COVID', 'Lung Opacity', 'Normal', 'Viral Pneumonia'], 'classesLen': 4, 'upSampling': True}
2021-05-09 10:33:05,280 INFO    MainThread:14540 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2t9lldmm
2021-05-09 10:33:05,282 INFO    MainThread:14540 [wandb_run.py:finish():1197] finishing run tecai/MLP/2t9lldmm
